version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - dogsled
    - dupl
    - dupword
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
  disable:
    - bodyclose
    - contextcheck
    - containedctx
    - cyclop
    - depguard
    - godox
    - durationcheck
    - exhaustruct
    - ineffassign
    - ireturn
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - godot
    - nlreturn
    - nolintlint
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    revive:
      severity: warning
      rules:
        - name: atomic
        - name: line-length-limit
          severity: error
          arguments: [ 120 ]
    gosec:
      severity: high
      excludes:
        - G401
    paralleltest:
      ignore-missing: true

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
